### ISSUE TITLE
Keyframe-selectors cannot be merged

### ISSUE THREAD

**Issue by gurre** [georgeadamson/postcss-merge-selectors#2]
Keyframe-selectors cannot be merged as the current behavior. #1 

Source:
```css
.visible {
  opacity: 1;
}

@keyframes flash {
    50%, from, to {
        opacity: 1;
    }
    25%, 75% { 
        opacity: 0;
    }
}
```

Result:
```css
@keyframes flash {
  50%, from, to, .visible {
    opacity: 1;
  }
  25%, 75% { 
    opacity: 0; 
  }
}
```
